### ISSUE TITLE
Order the Hardware

### ISSUE THREAD

**Issue by rileycleavenger** [rileycleavenger/TheModernJukebox#2]
We need our hardware asap before the pre-alpha build.

- [x] [Adafruit AirLift – ESP32 WiFi Co-Processor Breakout Board](https://www.adafruit.com/product/4201)
- [x] [Aux Connector](https://www.adafruit.com/product/1699) 
- [x] [Bluetooth Transceiver](https://www.adafruit.com/product/2479?gclid=Cj0KCQjw1aOpBhCOARIsACXYv-dYxELkQrVSBz_FD_e_u70szgy9Mf9MZwtit7fA3p2mv14iAPuZssUaAlBcEALw_wcB)
- [x] [Adafruit 1.14" 240x135 Color TFT Display + MicroSD Card Breakout - ST7789](https://www.adafruit.com/product/4383)
- [ ] HDMI Out
- [x] 2 buttons

**Comment by blake-budd1** [comment]
ESP32 Board looking at to order:
https://www.adafruit.com/product/5400

**Comment by alexacole** [comment]
Hardware Orders
