### ISSUE TITLE
Change code to C++ for HTTP requests to get the first song in the front-end queue. 

### ISSUE THREAD

**Issue by blake-budd1** [rileycleavenger/TheModernJukebox#52]

**Comment by rileycleavenger** [comment]
https://github.com/rileycleavenger/TheModernJukebox/blob/SoftwareAlphaChanges/the-modern-jukebox-react-app/api/index.js
https://github.com/rileycleavenger/TheModernJukebox/blob/SoftwareAlphaChanges/the-modern-jukebox-react-app/src/services/QueuePostService.ts

**Comment by blake-budd1** [comment]
Able to now get only the first song from the queue. Then post the remaining queue back to api/addQueue. Updated code not yet pushed but working properly. Also, the queue is still displayed correctly on the front-end page under queue after the first one is removed.
